apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../../../../infrastructure/namespaces/monitoring.yaml

# Note: Monitoring stack deployment via Helm will be configured separately
# This can reference a HelmRelease resource or Kustomize overlay

