apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Reference the monitoring namespace from infrastructure
  - ../../../../infrastructure/namespaces/monitoring.yaml
  
  # Note: The monitoring stack is deployed via ArgoCD Application
  # See: argocd/applications/monitoring-stack.yaml
  # It uses the kube-prometheus-stack Helm chart with values from
  # apps/monitoring-stack/values.yaml

commonLabels:
  app: monitoring
  managed-by: argocd
  environment: dev
