apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/sample-saas-app-platform/kustomization.yaml
  - apps/sample-saas-app-analytics/kustomization.yaml
  - apps/monitoring-stack/kustomization.yaml
  - infrastructure/kustomization.yaml

