apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
  - ../base

namePrefix: canary-

replicas:
  - name: app
    count: 1  # 10% of traffic initially

commonLabels:
  version: canary

images:
  - name: sample-app
    newTag: v1.1.0

