apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-blue

resources:
  - ../base

namePrefix: blue-

commonLabels:
  version: blue
  environment: blue

patches:
  - patch: |-
      - op: add
        path: /spec/template/metadata/labels/version
        value: blue
    target:
      kind: Deployment

