apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../bootstrap/flux-system/gotk-components.yaml
  - ../../../bootstrap/flux-system/gotk-sync.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/url
        value: https://github.com/SaaSInfraLab/flux-gitops-pipeline
    target:
      kind: GitRepository
      name: flux-system

