apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-saas-app-analytics
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/sample-saas-app/overlays/analytics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  timeout: 5m0s

