apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
  - ../base

namePrefix: stable-

replicas:
  - name: app
    count: 9  # 90% of traffic

commonLabels:
  version: stable

images:
  - name: sample-app
    newTag: v1.0.0

