apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: NAMESPACE

resources:
  - resource1.yaml
  - resource2.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: APP_NAME

# Image transformations
images:
  - name: IMAGE_NAME
    newName: NEW_IMAGE_NAME
    newTag: NEW_TAG

# Replica count overrides
replicas:
  - name: deployment-name
    count: 2

# Patches for resource modifications
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: deployment-name

